COMPONENT_SRCDIRS := bsec/src/bme680 pcd8544
COMPONENT_ADD_INCLUDEDIRS := bsec/src/bme680 bsec/src/inc pcd8544/include
COMPONENT_ADD_LDFLAGS += $(COMPONENT_PATH)/bsec/src/esp32/libalgobsec.a

CFLAGS += -DCONFIG_PCD8544_TRANS_QUEUE_SIZE=96
CFLAGS += -DCONFIG_PCD8544_BIAS_SYSTEM=7
CFLAGS += -DCONFIG_PCD8544_TEMPERATURE_COEFFICIENT=2